//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Destructor.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class Destructor extends Nave {

	private int Ataque;
	private Planeta Objetivo;
	public void Atacar() {
	
	}
	
	public void AumentarNivel() {
	
	}

	public Planeta getObjetivo() {
		return Objetivo;
	}

	public void setObjetivo(Planeta objetivo) {
		Objetivo = objetivo;
	}

	public int getAtaque() {
		return Ataque;
	}

	public void setAtaque(int ataque) {
		Ataque = ataque;
	}
	
	public Destructor(int demoraProduccion, Planeta destino, EstadoNave estado,
			int costo, int salud, Posicion pos, int ataque, Planeta objetivo) {
		super(demoraProduccion, destino, estado, costo, salud, pos);
		Ataque = ataque;
		Objetivo = objetivo;
	}
}
