//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ElementosDelEspacio.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public abstract class ElementosDelEspacio {
	private int personas;
	private String nombre;
	public void avanzarTurno() {
	
	}
	public int getPersonas() {
		return personas;
	}
	public void setPersonas(int personas) {
		this.personas = personas;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
