import java.util.Date;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Juego.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class Juego {
	private List<Jugador> Jugadores;
	private String Estado;
	private Date HoraInicio;
	private List<ElementosDelEspacio> elementos;
	public void avanzarRonda() {
	
	}
	
	public Juego(List<Jugador> gamers){
		this.Jugadores = gamers;	
	}
	public String toString() {
		return null;
	
	}
	
	public void inicializarEscenario(List<Jugador> Jugadores, List<Planeta> Planetas) {
		for (Planeta planeta : Planetas) {
			planeta.setPoblacion(10);
			planeta.setCantidadPersonas(10);
			planeta.setRecursos(80);
			planeta.setCantNaves(0);
			planeta.setCantTorretas(0);
		}
		
		for (Jugador jugador : Jugadores) {
			jugador.setCantPlanetas(0);
			jugador.setEstado("Esperando turno");
			jugador.setTorretasDestruidas(0);
			jugador.setNavesDestruidas(0);
			jugador.setRecursosProducidos(0);
		}
	}

	public List<Jugador> getJugadores() {
		return Jugadores;
	}

	public void setJugadores(List<Jugador> jugadores) {
		Jugadores = jugadores;
	}

	public Date getHoraInicio() {
		return HoraInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		HoraInicio = horaInicio;
	}

	public String getEstado() {
		return Estado;
	}

	public void setEstado(String estado) {
		Estado = estado;
	}

	public List<ElementosDelEspacio> getElementos() {
		return elementos;
	}

	public void setElementos(List<ElementosDelEspacio> elementos) {
		this.elementos = elementos;
	}
}
