import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jugador.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class Jugador {
	private String Estado;
	private int NavesDestruidas;
	private int CantPlanetas;
	private List<Planeta> Planetas;
	private int TorretasDestruidas;
	private int RecursosProducidos;
	private String Nombre;
	
	public Jugador(String nombre){
		this.Nombre = nombre;
	}
	public String toString() {
		return null;
	
	}
	
	public void avanzarTurno() {
	
	}

	public Object getEstado() {
		return Estado;
	}

	public void setEstado(String estado) {
		Estado = estado;
	}

	public Object getNavesDestruidas() {
		return NavesDestruidas;
	}

	public void setNavesDestruidas(int navesDestruidas) {
		NavesDestruidas = navesDestruidas;
	}

	public Object getCantPlanetas() {
		return CantPlanetas;
	}

	public void setCantPlanetas(int cantPlanetas) {
		CantPlanetas = cantPlanetas;
	}

	public List<Planeta> getPlanetas() {
		return Planetas;
	}

	public void setPlanetas(List<Planeta> planetas) {
		Planetas = planetas;
	}

	public Object getTorretasDestruidas() {
		return TorretasDestruidas;
	}

	public void setTorretasDestruidas(int torretasDestruidas) {
		TorretasDestruidas = torretasDestruidas;
	}

	public Object getRecursosProducidos() {
		return RecursosProducidos;
	}

	public void setRecursosProducidos(int recursosProducidos) {
		RecursosProducidos = recursosProducidos;
	}

	public Object getNombre() {
		return Nombre;
	}

	public void setNombre(String nombre) {
		Nombre = nombre;
	}
}
