//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NaveBatalla.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class NaveBatalla extends Nave {


	private int Ataque;
	private Nave Objectivo;
	public void Atacar() {
	
	}
	
	public void AumentarNivel() {
	
	}

	public int getAtaque() {
		return Ataque;
	}

	public void setAtaque(int ataque) {
		Ataque = ataque;
	}

	public Nave getObjectivo() {
		return Objectivo;
	}

	public void setObjectivo(Nave objectivo) {
		Objectivo = objectivo;
	}
	
	public NaveBatalla(int demoraProduccion, Planeta destino,
			EstadoNave estado, int costo, int salud, Posicion pos) {
		super(demoraProduccion, destino, estado, costo, salud, pos);
		// TODO Auto-generated constructor stub
	}
}
