import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Normal.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class Normal extends Planeta {
	
	private int VelocidadDeCrecimiento=1;
	private int CapacidadDeProduccion=1;
	

	public Normal(String nombre, int poblacion, int produccion, int recursos,
			List<Nave> naves, int cantTorretas, int cantidadPersonas,
			List<Torreta> torretas, int cantNaves, Posicion pos) {
		super(nombre, poblacion, produccion, recursos, naves, cantTorretas,
				cantidadPersonas, torretas, cantNaves, pos);		
	}	
	
    public  void CrearNave(){
    	
    }
	
	public  void AumentarProduccion(){
		
	}
	
	public  void CrearTorreta(){
		
	}
	
	
	
	public int getCapacidadDeProduccion() {
		return this.CapacidadDeProduccion;
	}


	public int getVelocidadDeCrecimiento() {
		return VelocidadDeCrecimiento;
	}

	
}
