import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ParamosDeLava.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class ParamosDeLava extends Planeta {
	public ParamosDeLava(String nombre, int poblacion, int produccion,
			int recursos, List<Nave> naves, int cantTorretas,
			int cantidadPersonas, List<Torreta> torretas, int cantNaves,
			Posicion pos,int VelocidadDeCrecimiento, int CapacidadDeProduccion) {
		super(nombre, poblacion, produccion, recursos, naves, cantTorretas,
				cantidadPersonas, torretas, cantNaves, pos);
		// TODO Auto-generated constructor stub
	}

	

	private int VelocidadDeCrecimiento=10;
	private int CapacidadDeProduccion=10;
	
	
    public  void CrearNave(){
    	
    }
	
	public  void AumentarProduccion(){
		
	}
	
	public  void CrearTorreta(){
		
	}
	
	public int getVelocidadDeCrecimiento() {
		return VelocidadDeCrecimiento;
	}

	public void setVelocidadDeCrecimiento(int velocidadDeCrecimiento) {
		VelocidadDeCrecimiento = velocidadDeCrecimiento;
	}

	public int getCapacidadDeProduccion() {
		return CapacidadDeProduccion;
	}

	public void setCapacidadDeProduccion(int capacidadDeProduccion) {
		CapacidadDeProduccion = capacidadDeProduccion;
	}
}
