//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Posicion.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class Posicion {
	private float x;
	private float y;
	public float getX() {
		return x;
	}
	public Posicion(float x,float y) {
		super();
		this.x=x;
		this.y=y;
		
	}
	public void setX(float x) {
		this.x = x;
	}
	public float getY() {
		return y;
	}
	public void setY(float y) {
		this.y = y;
	}
}
