//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Torreta.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class Torreta {
	private Object ID;
	private Object Salud;
	private Object Costo;
	private Object Defensa;
	private Object Ataque;
	public void AumentarNivel() {
	
	}
	
	public void Atacar() {
	
	}

	public Object getID() {
		return ID;
	}

	public void setID(Object iD) {
		ID = iD;
	}

	public Object getSalud() {
		return Salud;
	}

	public void setSalud(Object salud) {
		Salud = salud;
	}

	public Object getCosto() {
		return Costo;
	}

	public void setCosto(Object costo) {
		Costo = costo;
	}

	public Object getDefensa() {
		return Defensa;
	}

	public void setDefensa(Object defensa) {
		Defensa = defensa;
	}

	public Object getAtaque() {
		return Ataque;
	}

	public void setAtaque(Object ataque) {
		Ataque = ataque;
	}
}
