import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tundra.java
//  @ Date : 17/05/2017
//  @ Author : 
//
//




public class Tundra extends Planeta {
	private int VelocidadDeCrecimiento=5;
	private int CapacidadDeProduccion=5;
	
	
    public  void CrearNave(){
    	
    }
	
	public  void AumentarProduccion(){
		
	}
	
	public  void CrearTorreta(){
		
	}
	

	

	public Tundra(String nombre, int poblacion, int produccion, int recursos,
			List<Nave> naves, int cantTorretas, int cantidadPersonas,
			List<Torreta> torretas, int cantNaves, Posicion pos,int VelocidadDeCrecimiento, int CapacidadDeProduccion ) {
		super(nombre, poblacion, produccion, recursos, naves, cantTorretas,
				cantidadPersonas, torretas, cantNaves, pos);
		
		this.CapacidadDeProduccion=CapacidadDeProduccion;
		this.VelocidadDeCrecimiento=VelocidadDeCrecimiento;
	}


	public int getVelocidadDeCrecimiento() {
		return this.VelocidadDeCrecimiento;
		
	}

	public void setVelocidadDeCrecimiento(int velocidadDeCrecimiento) {
		this.VelocidadDeCrecimiento = velocidadDeCrecimiento;
	}

	public int getCapacidadDeProduccion() {
		return this.CapacidadDeProduccion;
	}

	public void setCapacidadDeProduccion(int capacidadDeProduccion) {
		this.CapacidadDeProduccion = capacidadDeProduccion;
	}
}
